language: node_js
node_js: '7'
cache:
  directories:
  - node_modules
script:
 - npm run build
 - npm run docs
deploy:
  - provider: npm
    skip_cleanup: true
    email: Serban.Petrescu@outlook.com
    api_key:
      secure: Cn/BC1sdD6hpy85xJB9+HwOikAB2OUH34ayb+X5uU3s1RExAWWrLwa3DhSRsBEJF5GFv443/+rZH2RYs3VVFEoKpR5+wBZ0eSfyqhLGRj4Fmz3FDGDWMxhX6aiXN1hVzB22sYWnvIk3GwxObZxybroZM8BI2n+AzZw/jvGjPEygiIaTuPLIg7ieplm1A43jEhbM9lhSVS1nuY4KZObcbEgf36cm+0y07q9Uol0AYKsntrt+nZNVRVY+jfhhiAjsMnJUBgyrQAFr9JLyCA+5rdd3HcD6jLuC8pqO/5pr9vuQg+5nLJ0Fdz4l1GjEHPBR3pbTPgwFLpQecQq74pKDvgZMgVDYXBqUUp/B0hERi/s2jc3LamccnIeLYSGwp4cyf8nzaMCQR7oTErGQ0hXC3E8IZeVrHIs85z1lNL4/6J+Fdfm1A2eLL1Ln8W8ZrRoS5exaCQXWA9cKP8nqQwFg1mqLuNqoEYlzPcyMl8vVZahehUaglTotoIYTeuUeo0fjT1hObVps7IdrGk50bpwUCgxA+maJc1qftojAKMvHW2s/OogjqTm4pnkWQleBw980aSfOllEfV5BD/LxYKhzYcLeHySndu6yE7Co7PLy9MDnDM9RSHrD6ukMIVxtzpMw86qW//7oiDNl1RU5uxH26q2SjvsMBkPCFecVNnWHiyihs=
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
